version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - api_worker_frontend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    restart: unless-stopped

    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

    networks:
      - api_worker_frontend
    depends_on:
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3001:3000"
    restart: unless-stopped
    networks:
      - api_worker_frontend

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: worker
    restart: unless-stopped

    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}

    networks:
      - api_worker_frontend

    depends_on:
      redis:
        condition: service_healthy

networks:
  api_worker_frontend:
    name: api_worker_frontend
    driver: bridge
