version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      REDIS_HOST: ${REDIS_HOST}
    networks:
      - api_worker_frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3001:3000"
    restart: unless-stopped
    networks:
      - api_worker_frontend

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: worker
    restart: unless-stopped
    environment:
      REDIS_HOST: ${REDIS_HOST}
    networks:
      - api_worker_frontend

networks:
  api_worker_frontend:
    external: true
