name: HNG14-STAGE2-DEVOPS

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: oxblixxx:5000
  IMAGE_PREFIX: job-tracker

jobs:
  PYTHON-LINT:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Python lint deps
        run: pip install flake8
      - name: Run flake8
        run: flake8 .

  ESLINT:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install eslint
        run: npm install -g eslint
      - name: Run eslint
        working-directory: frontend
        run: npx eslint .

  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Dockerfiles
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile 

  test:
    runs-on: ubuntu-latest
    needs: [PYTHON-LINT, ESLINT, hadolint]
    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          pip install -r requirements.txt pytest pytest-cov fakeredis
      - name: Run tests with coverage
        run: pytest --cov=app --cov-report=xml
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

  # build-push:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: Login to Registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ${{ env.REGISTRY }}
  #         username: ${{ secrets.REGISTRY_USERNAME }}
  #         password: ${{ secrets.REGISTRY_PASSWORD }}
  #     - name: Build and push
  #       uses: docker/build-push-action@v6
  #       with:
  #         context: .
  #         push: true
  #         tags: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}:${{ github.sha }},${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}:latest
  #         cache-from: type=gha
  #         cache-to: type=gha,mode=max
